default: &default
  adapter: postgresql
  encoding: unicode
  username: shop_api
  password: shop_api
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_api_development

test:
  <<: *default
  database: shop_api_test
